### ISSUE TITLE
Compilation Error in Master and Release 1.0.0

### ISSUE THREAD

**Issue by mayhew64** [joeattardi/github-pr-dashboard#13]
Relatively new to Node, npm, & JS.  Apologize if this is some user config issue....
Downloaded release
npm install
npm run dev-build
npm run start 

Using a clone from Master and the also tried with the latest release 1.0.0.

> ERROR in ./src/js/components/Dashboard.jsx
> 
> /Users/bruce/Downloads/github-pr-dashboard-1.0.0/src/js/components/Dashboard.jsx
>   8:8  error  'RepoIndicator' is defined but never used  no-unused-vars
> 
> ✖ 1 problem (1 error, 0 warnings)

After removing the RepoIndicator, the compilation completes.  When accessing the webpage:

Chrome: A spinning load icon
Safari: UI loads but no data
Firefox: A Spinning load icon

Also to note:

> WARNING in ./src/js/components/AddRepo.jsx
> 
> /Users/bruce/Downloads/github-pr-dashboard-1.0.0/src/js/components/AddRepo.jsx
>   57:13  warning  Unexpected console statement  no-console
> 
> ✖ 1 problem (0 errors, 1 warning)

**Comment by joeattardi** [comment]
This is totally my fault, sorry about that. The README is woefully out of date. I will update it. In the meantime, you can get up and running by running `node server/index.js` then accessing http://localhost:8080

Sorry again!

**Comment by mayhew64** [comment]
Thank you, the latest pull is now showing I have a 401 error.   I'll go back to your config to see if that works.

**Comment by joeattardi** [comment]
Updated the README and fixed the lint errors. Let me know if you have further questions!
